jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    on: push
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Hello World"
